### ISSUE TITLE
Uncaught Error: The `useSlate` hook must be used inside the <Slate> component's context.

### ISSUE THREAD

**Issue by geohuz** [slate-solid/slate-solid#79] opened 2024-11-18 06:43 UTC
I have a sample project hosted in https://stackblitz.com/edit/solidjs-templates-syxyom?file=src%2FApp.jsx , the console shows 

```
Uncaught Error: The `useSlate` hook must be used inside the <Slate> component's context.
    at useSlate (useSlate.jsx:9:15)
    at _$$component.location (App.jsx:249:18)
    at @solid-refresh:25:42
    at untrack (chunk-FVPZWHC4.js?v=2300f59c:484:12)
    at HMRComp.createMemo.name [as fn] (@solid-refresh:25:28)
    at runComputation (chunk-FVPZWHC4.js?v=2300f59c:761:22)
    at updateComputation (chunk-FVPZWHC4.js?v=2300f59c:740:3)
    at createMemo (chunk-FVPZWHC4.js?v=2300f59c:266:10)
    at [solid-refresh]MarkButton (@solid-refresh:22:20)
    at chunk-FVPZWHC4.js?v=2300f59c:599:14
```

Couldn't find the solution

**Comment by bmingles** [comment] 2024-11-18 14:09
@geohuz It looks like you have the `slate-dom` preview package installed. First thing to do would be to switch to `slate-dom` `^0.111.0` which has been published by the official slate repo now. After changing that, I see other errors that make me think Stackblitz may not currently work with SolidJS. Do you have any other examples that are actually working?

**Comment by bmingles** [comment] 2024-11-18 14:33
hmm, I was able to reproduce locally by downloading the Stackblitz. Will have to dig in to see what's different than examples that are working.

**Comment by bmingles** [comment] 2024-11-19 03:48
It looks like the problem is that the children are rendering before the <Slate/> component. This works fine in the source repo, but seems to be an issue when installing from npm. Possible it's a packaging / bundling issue, but TBD

**Comment by geohuz** [comment] 2024-11-19 15:03
@bmingles I'm able to run the app correctly in my local project, after installing the slate-dom:

```json
  "dependencies": {
    ...
    "slate-dom": "^0.111.0",
    ...
  },
```

**Comment by bmingles** [comment] 2024-11-19 15:09
@geohuz Interesting. I get the error even after installing slate-dom. Did you do anything additional with your vite config? I think I did not properly bundle the npm package as a library.

**Comment by bmingles** [comment] 2024-11-20 15:02
The `useSlate` error should be fixed in https://www.npmjs.com/package/@slate-solid/core/v/1.0.13

I've created [Turn off debug logging by default #82](https://github.com/slate-solid/slate-solid/issues/82) to address the console logging.

**Closed by bmingles** 2024-11-20 15:02 UTC
